name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_IMAGE }}:latest
          build-args: |
            PGPORT=${{ secrets.PGPORT }}
            PGPASSWORD=${{ secrets.PGPASSWORD }}
            PGUSER=${{ secrets.PGUSER }}
            PGHOST=${{ secrets.PGHOST }}
            PGDATABASE=${{ secrets.PGDATABASE }}
